"""
This type stub file was generated by pyright.
"""

import click
from .core import ClickHandler, ColorFormatter, basic_config
from .options import simple_verbosity_option

__version__ = ...
if not hasattr(click, 'get_current_context'):
    ...
