"""
This type stub file was generated by pyright.
"""

def simple_verbosity_option(logger=..., *names, **kwargs): # -> Callable[..., Any]:
    '''A decorator that adds a `--verbosity, -v` option to the decorated
    command.

    Name can be configured through ``*names``. Keyword arguments are passed to
    the underlying ``click.option`` decorator.
    '''
    ...

