"""
This type stub file was generated by pyright.
"""

from collections.abc import AsyncIterator, Awaitable, Callable, Iterator
from contextlib import AbstractAsyncContextManager, AbstractContextManager
from types import TracebackType
from typing import (
    IO,
    Any,
    TypeAlias,
    TypeVar,
    overload,
)

from typing_extensions import ParamSpec, Protocol, Self

_T = TypeVar("_T")
_T_co = TypeVar("_T_co", covariant=True)
_T_io = TypeVar("_T_io", bound=IO[str] | None)
_F = TypeVar("_F", bound=Callable[..., Any])
_P = ParamSpec("_P")
_ExitFunc: TypeAlias = Callable[
    [type[BaseException] | None, BaseException | None, TracebackType | None],
    bool,
]
_CM_EF = TypeVar("_CM_EF", AbstractContextManager[Any], _ExitFunc)

class _GeneratorContextManager(AbstractContextManager[_T_co]):
    def __call__(self, func: _F) -> _F: ...

def contextmanager(
    func: Callable[_P, Iterator[_T]],
) -> Callable[_P, _GeneratorContextManager[_T]]: ...
def asynccontextmanager(
    func: Callable[_P, AsyncIterator[_T]],
) -> Callable[_P, AbstractAsyncContextManager[_T]]: ...

class _SupportsClose(Protocol):
    def close(self) -> object: ...

_SupportsCloseT = TypeVar("_SupportsCloseT", bound=_SupportsClose)

class closing(AbstractContextManager[_SupportsCloseT]):
    def __init__(self, thing: _SupportsCloseT) -> None: ...

class _SupportsAclose(Protocol):
    async def aclose(self) -> object: ...

_SupportsAcloseT = TypeVar("_SupportsAcloseT", bound=_SupportsAclose)

class aclosing(AbstractAsyncContextManager[_SupportsAcloseT]):
    def __init__(self, thing: _SupportsAcloseT) -> None: ...

_AF = TypeVar("_AF", bound=Callable[..., Awaitable[Any]])

class AsyncContextDecorator:
    def __call__(self, func: _AF) -> _AF: ...

class suppress(AbstractContextManager[None]):
    def __init__(self, *exceptions: type[BaseException]) -> None: ...
    def __exit__(
        self,
        exctype: type[BaseException] | None,
        excinst: BaseException | None,
        exctb: TracebackType | None,
    ) -> bool: ...

class redirect_stdout(AbstractContextManager[_T_io]):
    def __init__(self, new_target: _T_io) -> None: ...

class redirect_stderr(AbstractContextManager[_T_io]):
    def __init__(self, new_target: _T_io) -> None: ...

class ContextDecorator:
    def __call__(self, func: _F) -> _F: ...

class ExitStack(AbstractContextManager[ExitStack]):
    def __init__(self) -> None: ...
    def enter_context(self, cm: AbstractContextManager[_T]) -> _T: ...
    def push(self, exit: _CM_EF) -> _CM_EF: ...
    def callback(
        self, callback: Callable[..., Any], *args: Any, **kwds: Any
    ) -> Callable[..., Any]: ...
    def pop_all(self) -> Self: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        __exc_type: type[BaseException] | None,
        __exc_value: BaseException | None,
        __traceback: TracebackType | None,
        /,
    ) -> bool: ...

_ExitCoroFunc: TypeAlias = Callable[
    [
        type[BaseException] | None,
        BaseException | None,
        TracebackType | None,
    ],
    Awaitable[bool],
]
_CallbackCoroFunc: TypeAlias = Callable[..., Awaitable[Any]]
_ACM_EF = TypeVar("_ACM_EF", AbstractAsyncContextManager[Any], _ExitCoroFunc)

class AsyncExitStack(AbstractAsyncContextManager[AsyncExitStack]):
    def __init__(self) -> None: ...
    def enter_context(self, cm: AbstractContextManager[_T]) -> _T: ...
    def enter_async_context(
        self, cm: AbstractAsyncContextManager[_T]
    ) -> Awaitable[_T]: ...
    def push(self, exit: _CM_EF) -> _CM_EF: ...
    def push_async_exit(self, exit: _ACM_EF) -> _ACM_EF: ...
    def callback(
        self, callback: Callable[..., Any], *args: Any, **kwds: Any
    ) -> Callable[..., Any]: ...
    def push_async_callback(
        self, callback: _CallbackCoroFunc, *args: Any, **kwds: Any
    ) -> _CallbackCoroFunc: ...
    def pop_all(self) -> Self: ...
    def aclose(self) -> Awaitable[None]: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        __exc_type: type[BaseException] | None,
        __exc_value: BaseException | None,
        __traceback: TracebackType | None,
        /,
    ) -> bool: ...

class nullcontext(AbstractContextManager[_T]):
    enter_result: _T
    @overload
    def __init__(self: nullcontext[None], enter_result: None = ...) -> None: ...
    @overload
    def __init__(self: nullcontext[_T], enter_result: _T) -> None: ...
    def __enter__(self) -> _T: ...
    def __exit__(self, *exctype: object) -> bool: ...
